version: '2'
services:
  de-kit-platform-app-registry-etcd:
    image: quay.io/coreos/etcd
    command:
      - /usr/local/bin/etcd
      - "-advertise-client-urls=http://0.0.0.0:49501"
      - "-listen-client-urls=http://0.0.0.0:49501"
    ports:
      - "49501:49501"
    environment:
      - ETCD_CORS=*
  de-kit-platform-app-registry-etcd-browser:
    image: ${DOCKER_REGISTRY_ADDRESS}/de-kit-platform-app-registry-etcd-browser:v1.0.0
    ports:
      - "49502:49502"
    environment:
      ETCD_HOST: ${HOST_IP}
      ETCD_PORT: 49501
  com-iao-platform-app-registry-etcd-api:
    image: ${DOCKER_REGISTRY_ADDRESS}/com-iao-platform-app-registry-etcd-api:v1.0.0
    ports:
      - "49503:49503"
    secrets:
      - sslcert
      - sslkey
    environment:
      SERVER_PROTOCOL: https
      HOST_IP: ${HOST_IP}
      SSL_CERT: /run/secrets/sslcert
      SSL_KEY: /run/secrets/sslkey
      LOG_LEVEL_CONSOLE: ${LOG_LEVEL_CONSOLE}
      LOG_LEVEL_FILE: ${LOG_LEVEL_FILE}
      ETCD_ADDRESS: "${HOST_IP}:49501"
    restart: always
secrets:
  sslkey:
    external: true
  sslcert:
    external: true