version: '2'
services:
  app-registry-etcd-wrapper:
    image: scaleit-app-pool.ondics.de:5000/scaleit-app-pool/etcd-api-wrapper:1.0
    build: "server/."
    ports:
      - "49503:49503"
    environment:
      SERVER_PROTOCOL: https
    restart: always
