version: '3.1'
services:

  app-registry-mongodb:
    image: app-registry-mongodb
    build:
      dockerfile: ./docker/DomainSoftware/app-registry-mongodb/Dockerfile
    ports:
      - "${EXPOSED_SERVER_PORT}:49501"
    secrets:
      - sslcert
      - sslkey
    environment:
      SERVER_PROTOCOL: https
      HOST_IP: ${HOST_IP}
      SERVER_PORT: 10010
      SSL_CERT: /run/secrets/sslcert
      SSL_KEY: /run/secrets/sslkey
      LOG_LEVEL_CONSOLE: ${LOG_LEVEL_CONSOLE}
      LOG_LEVEL_FILE: ${LOG_LEVEL_FILE}
    restart: always

secrets:
  sslkey:
    file: ./server.key
  sslcert:
    file: ./server.crt