version: '2'
services:
  app-registry-mongodb:
    image: ${DOCKER_REGISTRY_ADDRESS}/app-registry-mongodb:v1.0.3
    ports:
      - "${EXPOSED_SERVER_PORT}:49501"
    secrets:
      - sslcert
      - sslkey
    environment:
      SERVER_PROTOCOL: https
      HOST_IP: ${HOST_IP}
      SERVER_PORT: 49501
      EXPOSED_SERVER_PORT: EXPOSED_SERVER_PORT
      SSL_CERT: /run/secrets/sslcert
      SSL_KEY: /run/secrets/sslkey
      LOG_LEVEL_CONSOLE: ${LOG_LEVEL_CONSOLE}
      LOG_LEVEL_FILE: ${LOG_LEVEL_FILE}
      MONGODB_ADDRESS: ${MONGODB_ADDRESS}
      MONGODB_USER: ${MONOGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DB: app-registry
    restart: always
secrets:
  sslkey:
    external: true
  sslcert:
    external: true