x-swagger-router-controller: apps
get:
  description: Get an app
  operationId: getApp
  parameters:
    - $ref: '../parameters.yaml#/parameters/id'
  responses:
    "200":
      description: Success
      schema:
        $ref: "../schemas/App.yaml"
    default:
      description: Error
      schema:
        $ref: "../Error.yaml"
put:
  description: Update an app
  operationId: updateApp
  parameters:
    - $ref: '../parameters.yaml#/parameters/id'
    - name: body
      description: App
      schema:
        type: object
      in: body
      required: true
  responses:
    "200":
      description: Success
      schema:
        $ref: "../schemas/App.yaml"
    default:
      description: Error
      schema:
        $ref: "../Error.yaml"
delete:
  description: Delete an app
  operationId: deleteApp
  parameters:
    - $ref: '../parameters.yaml#/parameters/id'
  responses:
    "200":
      description: Success
      schema:
        $ref: "../schemas/App.yaml"
    default:
      description: Error
      schema:
        $ref: "../Error.yaml"