version: '2'
services:
  com-iao-platform-app-registry-etcd-api:
    image: scaleit-app-pool.ondics.de:5000/scaleit-app-pool/com-iao-platform-app-registry-etcd-api:v1.0.0
    ports:
      - "50501:50501"
    secrets:
      - sslcert
      - sslkey
    environment:
      SERVER_PROTOCOL: https
      HOST_IP: ${HOST_IP}
      SERVER_PORT: 50501
      SSL_CERT: /run/secrets/sslcert
      SSL_KEY: /run/secrets/sslkey
      LOG_LEVEL_CONSOLE: ${LOG_LEVEL_CONSOLE}
      LOG_LEVEL_FILE: ${LOG_LEVEL_FILE}
      ETCD_ADDRESS: ${ETCD_ADDRESS}
    restart: always
secrets:
  sslkey:
    external: true
  sslcert:
    external: true