version: '3.1'
services:
  app-registry:
    image: ${DOCKER_REGISTRY_ADDRESS}/app-registry:v1.0.0
    build:
      context: ./../
      dockerfile: ./docker/PlatformEssentials/app-registry/Dockerfile
  app-registration-sidecar:
    image: ${DOCKER_REGISTRY_ADDRESS}/app-registration-sidecar:v1.0.0
    build:
      context: ./../
      dockerfile: ./docker/PlatformSidecars/app-registration-sidecar/Dockerfile