version: '3.1'
services:
  com-iao-platform-app-registry:
    image: ${DOCKER_REGISTRY_ADDRESS}/com-iao-platform-app-registry:v1.0.1
    build:
      context: ./../
      dockerfile: ./docker/PlatformEssentials/app-registry/Dockerfile
  com-iao-platform-app-registration-sidecar:
    image: ${DOCKER_REGISTRY_ADDRESS}/com-iao-platform-app-registration-sidecar:v1.0.0
    build:
      context: ./../
      dockerfile: ./docker/PlatformSidecars/app-registration-sidecar/Dockerfile