type: object
required:
  - id
  - name
  - title
  - shortDescription
  - appType
  - status
  - iconUrl
mongoose:options:
  timestamps: true
properties:
  id:
    type: string
    mongoose:unique: true
    example: com.ondics.app.pacman/pacman_1
  name:
    type: string
    example: com.ondics.app.pacman
  title:
    type: string
    example: Pacman
  shortDescription:
    type: string
    example: Pacman App of Ondics
  description:
    type: string
    example: Pacman App of Ondics with capabilities to reset scores
  category:
    type: string
    enum:
      - productivity
      - utilities
      - tools
      - development
      - connectivity
      - erp
      - camera
  appType:
    type: string
    enum:
      - domainApp
      - platformEssential
      - businessEssential
  status:
    type: string
    enum:
      - online
      - offline
      - upgrading
      - disabled
      - installing
      - error
      - blocking
  apiEntrypoint:
    type: string
    example: https://<ip>:<port>/api/v1
  apiSpecificationUrl:
    type: string
    example: https://<ip>:<port>/api/v1/specification
  adminUrl:
    type: string
    example: https://<ip>:<port>/admin
  userUrl:
    type: string
    example: https://<ip>:<port>/user
  iconUrl:
    type: string
    example: https://<ip>:<port>/user/icon.svg
  createdAt:
    type: string
    format: date-time
    mongoose: skipInSchemaDefinition
  updatedAt:
    type: string
    format: date-time
    mongoose: skipInSchemaDefinition
