type: object
required:
  - id
  - url
  - category
  - appType
  - lifecycleStatus
mongoose:options:
  timestamps: true
properties:
  id:
    type: string
    mongoose:unique: true
    example: com.ondics.app.pacman/pacman_1
  name:
    type: string
    example: com.ondics.app.pacman
  userUrl:
    type: string
    example: https://<ip>:<port>/user
  adminUrl:
    type: string
    example: https://<ip>:<port>/admin
  iconUrl:
    type: string
    example: https://<ip>:<port>/user/icon.svg
  title:
    type: string
    example: Pacman
  shortDescription:
    type: string
    example: 1 line
  description:
    type: string
    example: Pacman App von Ondics
  category:
    type: string
    enum:
      - productivity
      - utilities
      - tools
      - development
      - connectivity
      - service
      - erp
      - camera
  api:
    type: string
    todo: siehe hydra
  appType:
    type: string
    enum:
      - domainApp
      - platformEssential
      - businessEssential
  state:
    type: string
    enum:
      - online
      - offline
      - upgrading
      - disabled
      - installing
      - error
      - blocking
  createdAt:
      type: string
      format: date-time
  updatedAt:
    type: string
    format: date-time
