type: object
required:
  - id
  - url
  - category
  - appType
  - lifecycleStatus
mongoose:options:
  timestamps: true
properties:
  id:
    type: string
    mongoose:unique: true
  url:
    type: string
  description:
    type: string
  icon:
    type: string
  category:
    type: string
    enum:
      - productivity
      - utilities
      - tools
      - development
      - connectivity
      - service
      - erp
      - photo
  appType:
    type: string
    enum:
      - domainApp
      - platformEssential
      - businessEssential
  lifecycleStatus:
    type: string
    enum:
      - online
      - offline
      - upgrading
      - disabled
      - installing
      - error
      - blocking
  visibleForRole:
    type: array
    mongoose:ref: Role
    items:
      type: string
      format: uri
