id: "api/v1/definitions/schemas/App.yaml"
type: object
required:
  - id
  - name
  - title
  - shortDescription
  - appType
  - status
  - iconUrl
mongoose:options:
  timestamps: true
properties:
  id:
    type: string
    mongoose:unique: true
    example: com.ondics.app.pacman/pacman_1
  name:
    type: string
    example: com.ondics.app.pacman
  title:
    type: string
    example: Pacman
  shortDescription:
    type: string
    example: Pacman App of Ondics
  description:
    type: string
    example: Pacman App of Ondics with capabilities to reset scores
  category:
    type: string
    # temporarily disable category enum validation since final category names not yet defined
    #    enum:
    #      - productivity
    #      - utilities
    #      - tools
    #      - development
    #      - connectivity
    #      - erp
    #      - camera
    #      - spiele
  appType:
    type: string
    # temporarily add scaleit-app and scaleit-core-app as accepted appType
    enum:
      - domainApp
      - platformEssential
      - businessEssential
      - scaleit-app
      - scaleit-core-app
  status:
    type: string
    # temporarily add running as accepted status, needs to be removed
    enum:
      - online
      - offline
      - running
  apiEntrypoint:
    type: string
    example: https://<ip>:<port>/api/v1
  adminUrl:
    type: string
    example: https://<ip>:<port>/admin
  adminConfigUrl:
    type: string
    example: https://<ip>:<port>/admin#/config
  adminDocUrl:
    type: string
    example: https://<ip>:<port>/admin#/doc
  adminLogUrl:
    type: string
    example: https://<ip>:<port>/admin#/log
  adminStatusUrl:
    type: string
    example: https://<ip>:<port>/admin#/status
  userUrl:
    type: string
    example: https://<ip>:<port>/user
  userDocUrl:
    type: string
    example: https://<ip>:<port>/user#/doc
  userStatusUrl:
    type: string
    example: https://<ip>:<port>/user#/status
  devDocUrl:
    type: string
    example: https://<ip>:<port>/dev#/doc
  devSwaggerUrl:
    type: string
    example: https://<ip>:<port>/dev#/swagger
  iconUrl:
    type: string
    example: https://<ip>:<port>/user/icon.svg
  updatedAt:
    type: string
    #    format: date-time
