parameters:
  id:
    name: id
    description: id
    type: string
    in: path
    required: true
  offset:
    in: query
    name: offset
    required: false
    schema:
      type: integer
      minimum: 0
    description: The number of items to skip before starting to collect the result set.
  limit:
    in: query
    name: limit
    required: false
    schema:
      type: integer
      minimum: 1
      maximum: 100
      default: 20
    description: The numbers of items to return.
  language:
    in: header
    name: Accept-Language
    description: the language in which the result should be returned
    required: false
    type: string