swagger: "2.0"
info:
  version: "0.9.1"
  title: ScaleIT App Registry MongoDB
basePath: /api/v1
# 
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /health:
    $ref: 'api/definitions/paths/health.yaml'
  /apps:
    $ref: 'api/definitions/paths/apps.yaml'
  /apps/{id}:
    $ref: 'api/definitions/paths/app.yaml'
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  App:
    $ref: 'api/definitions/schemas/App.yaml'