swagger: "2.0"
info:
  version: "0.9.1"
  title: ScaleIT App Registry MongoDB
host: localhost:10010
basePath: /
# 
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/health:
    $ref: 'api/paths/health.yaml'
  /api/v1/apps:
    $ref: 'api/paths/apps.yaml'
  /api/v1/apps/{id}:
    $ref: 'api/paths/app.yaml'
  /swagger:
    x-swagger-pipe: swagger_raw
