swagger: "2.0"
info:
  version: "1.0.0"
  title: ScaleIT App Registry ETCD API
basePath: /api/v1
# 
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /health:
    $ref: 'api/paths/health.yaml'
  /apps:
    $ref: 'api/paths/apps.yaml#/apps'
  /apps/{id}:
    $ref: 'api/paths/apps.yaml#/appsId'
  /apps/schema:
    $ref: 'api/paths/apps.yaml#/appsSchema'
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  App:
    $ref: 'api/definitions/schemas/App.yaml'