.catalog:
  name: App Registry ETCD API
  version: "v1.0.0"
  description: "Description of App Registry ETCD API"
  minimum_rancher_version: v1.1.0
  questions:
    - variable: HOST_IP
      label: "Host IP"
      description: |
        Host IP Address
      type: "string"
      required: true
      default: "localhost"
    - variable: LOG_LEVEL_CONSOLE
      label: "Log level console"
      description: |
        Determine log level of console
      required: true
      type: enum
      default: debug
      options:
        - error
        - warn
        - info
        - verbose
        - debug
        - silly
        - none
    - variable: LOG_LEVEL_FILE
      label: "Log level file (server-log.log)"
      description: |
        Determine log level of file
      required: true
      type: enum
      default: warn
      options:
        - error
        - warn
        - info
        - verbose
        - debug
        - silly
        - none
    - variable: ETCD_ADDRESS
      label: "ETCD Address"
      description: |
        Address of the ETCD
      required: true
      default: "localhost:49501"