.catalog:
  name: ERP-Proxy Dummy
  version: "v1.0.2"
  description: "ERP-Proxy Dummy description"
  minimum_rancher_version: v1.1.0
  questions:
    - variable: DOCKER_REGISTRY_ADDRESS
      label: "Docker Registry Address"
      description: |
        Address for Docker Registry where the images are available
      type: "string"
      required: true
      default: "localhost:5000"
    - variable: HOST_IP
      label: "Host IP"
      description: |
        Host IP Address
      type: "string"
      required: true
      default: "localhost"
    - variable: EXPOSED_SERVER_PORT
      label: "Exposed Server Port"
      description: |
        Port that is exposed on the host system
      type: "string"
      required: true
      default: "49501"
    - variable: LOG_LEVEL_CONSOLE
      label: "Log level console"
      description: |
        Determine log level of console
      required: true
      type: enum
      default: debug
      options:
        - error
        - warn
        - info
        - verbose
        - debug
        - silly
        - none
    - variable: LOG_LEVEL_FILE
      label: "Log level file (server-log.log)"
      description: |
        Determine log level of file
      required: true
      type: enum
      default: warn
      options:
        - error
        - warn
        - info
        - verbose
        - debug
        - silly
        - none
    - variable: MONGODB_ADDRESS
      label: "MongoDB Address"
      description: |
        Address of the MongoDB
      required: true
      default: "localhost:27017"
    - variable: MONGODB_USER
      label: "MongoDB User"
      description: |
        MongoDB User
      type: "string"
      required: false
      default: ""
    - variable: MONGODB_PASSWORD
      label: "MongoDB Password"
      description: |
        MongoDB Password
      type: "string"
      required: false
      default: ""